MODULE EmployeeDop;

REQUIRE EmployeeNew;

NAMESPACE Contact;

dateDismissal 'Дата увольнения' = DATA DATE (Employee);
isFillingTime 'Заполнение времени' = DATA BOOLEAN (Employee);

EXTEND FORM employees
    PROPERTIES(o) READONLY dateDismissal, isFillingTime
;

EXTEND FORM employee
    PROPERTIES(o) dateDismissal, isFillingTime
;

DESIGN employee {
    OBJECTS {
        dop3 {
            MOVE PROPERTY (dateDismissal(o)) AFTER PROPERTY (employmentDate(o));
        }
        note {
            MOVE PROPERTY (isFillingTime(o)) AFTER PROPERTY (inactive(o));
        }
    }
}

CLASS Child 'Дети';
name 'Имя' = DATA STRING[50] (Child) ;
date 'Дата рождения' = DATA DATE (Child) ;
employee = DATA Employee (Child) NONULL AUTOSET;
lastNameEmployee 'Сотрудник' (Child c) = lastName(employee(c));

EXTEND FORM employees
    OBJECTS c = Child
    PROPERTIES(c) READONLY date, name, lastNameEmployee
    ORDERS date(c)
    FILTERGROUP childEmployee
        FILTER 'По сотруднику' employee(c)=o DEFAULT
;

EXTEND FORM employee
    OBJECTS c = Child
    PROPERTIES(c) name, date
    PROPERTIES(c) NEW, DELETE
    ORDERS date(c)
    FILTERS employee(c)=o
;
