MODULE SoftwareModules;

REQUIRE MasterData;

NAMESPACE SoftwareModules;

CLASS ComputerProgram 'Компьютерная программа';
TABLE computerProgram (ComputerProgram);

code 'Код' = DATA STRING[20] (ComputerProgram);
name 'Наименование программы' = DATA STRING[200] (ComputerProgram);

CLASS SoftwareModule 'Программный модуль';
TABLE softwareModule (SoftwareModule);

computerProgram = DATA ComputerProgram (SoftwareModule) AUTOSET;
nameComputerProgram 'Наименование программы' (SoftwareModule s) = name(computerProgram(s));
code 'Код' = DATA STRING[20] (SoftwareModule);
name 'Наименование модуля' = DATA STRING[200] (SoftwareModule);
dateEntry 'Дата ввода' = DATA DATE (SoftwareModule);

CLASS SubModule 'Подмодуль';
TABLE subModule (SubModule);

softwareModule = DATA SoftwareModule (SubModule) AUTOSET;
nameSoftwareModule 'Наименование модуля' (SubModule sm) = name(softwareModule(sm));
code 'Код' = DATA STRING[20] (SubModule);
name 'Наименование подмодуля' = DATA STRING[200] (SubModule);
dateEntry 'Дата ввода' = DATA DATE (SubModule);

FORM computerProgram 'Компьютерная программа'
    OBJECTS c = ComputerProgram PANEL
    PROPERTIES(c) code, name
    
    EDIT ComputerProgram OBJECT c
;

FORM softwareModule 'Программный модуль'
    OBJECTS s = SoftwareModule PANEL
    PROPERTIES(s) code, name, dateEntry
    
    EDIT SoftwareModule OBJECT s
;

FORM subModule 'Подмодуль'
    OBJECTS sm = SubModule PANEL
    PROPERTIES(sm) code, name, dateEntry

    EDIT SubModule OBJECT sm
;

FORM softwareModules 'Программные модули'
    OBJECTS c = ComputerProgram 
    PROPERTIES(c) READONLY code, name
    PROPERTIES (c) NEWSESSION NEW, EDIT, DELETE
    ORDERS code(c), name(c)
    
    OBJECTS s = SoftwareModule
    PROPERTIES(s) READONLY code, name, dateEntry
    PROPERTIES (s) NEWSESSION NEW, EDIT, DELETE
    ORDERS code(s), name(s)
    FILTERGROUP cp FILTER 'По компьютерной программе' computerProgram(s)=c DEFAULT

    OBJECTS sm = SubModule
    PROPERTIES(sm) READONLY code, name, dateEntry
    PROPERTIES (sm) NEWSESSION NEW, EDIT, DELETE
    ORDERS code(sm), name(sm)
    FILTERGROUP mod FILTER 'По программному модулю' softwareModule(sm)=s DEFAULT
;

DESIGN softwareModules {
    MOVE BOX(c) {fill=1;}
    MOVE BOX(s) {fill=8;}
    MOVE BOX(sm) {fill=8;}
    MOVE TOOLBARBOX;
}

NAVIGATOR {
    templatesNavigator {
        NEW softwareModules;
    }
}

select 'Отм.' = DATA LOCAL NESTED BOOLEAN (SoftwareModule);
select 'Отм.' = DATA LOCAL NESTED BOOLEAN (SubModule);

FORM softwareModulesDialog 'Программные модули'
    OBJECTS c = ComputerProgram
    PROPERTIES(c) READONLY code, name
    ORDERS code(c), name(c)
    
    OBJECTS s = SoftwareModule
    PROPERTIES(s) select
    PROPERTIES(s) READONLY code, name, dateEntry
    ORDERS code(s), name(s)
    FILTERGROUP cp FILTER 'По компьютерной программе' computerProgram(s)=c DEFAULT

    OBJECTS sm = SubModule
    PROPERTIES(sm) select
    PROPERTIES(sm) READONLY code, name, dateEntry
    ORDERS code(sm), name(sm)
    FILTERGROUP mod FILTER 'По программному модулю' softwareModule(sm)=s DEFAULT
;

DESIGN softwareModulesDialog {
    MOVE BOX(c) {fill=1;}
    MOVE BOX(s) {fill=8;}
    MOVE BOX(sm) {fill=8;}
    MOVE TOOLBARBOX;
}
