MODULE PatternWordDop;

REQUIRE PatternWord, SoftwareModules;

setTextDop 'Формировать значение' (TemplateEntry te) {
    DIALOG softwareModulesDialog OBJECTS c INPUT DO {
        value(te) <- name(c);
        FOR select(SoftwareModule s) DO {
            value(te) <- value(te) + '\n' + name(s);
            select(s) <- NULL;
        }
    }     
}

EXTEND FORM editTemplate
    PROPERTIES SHOWIF key(te)='ZABZ1' setTextDop(te)
;

