MODULE DebtDashboardDop;

REQUIRE DebtDashboardNew;

NAMESPACE Contract;

paidAgreementDop 'Оплачено' (Debt d, DATE dt) = PARTITION UNGROUP paidPayment
    LIMIT STRICT sum(d) IF date(d)<=dt
    ORDER date(d),d
    BY agreement(d), dt;

paidNotDebtDop (Contract c, DATE dt) = paid(c, dt) (-) [GROUP SUM paidAgreementDop(Debt d, dt) BY contract(d)](c);

paidContractDop 'Оплачено' (Debt d, DATE dt) = PARTITION UNGROUP paidNotDebtDop
    LIMIT STRICT (sum(d) (-) paidAgreementDop(d, dt)) IF NOT agreement(d) AND date(d)<=dt
    ORDER date(d),d
    BY contract(d), dt;

paidDop 'Оплачено' (Debt d, DATE dt) = paidAgreementDop(d, dt) (+) paidContractDop(d, dt);

sumDebtDop 'Сумма задолженностей' (Customer c, ContractType t, DATE d) =
    GROUP SUM sum(Debt dd) (-) paidDop(dd, d) IF date(dd) <= d AND NOT inactive(dd) BY customer(dd), type(contract(dd));

balanceDop (Debt db, DATE d) = sum(db) (-) paidDop(db,d);

FORM reportNegativeDebts 'Скрытые переплаты'
    OBJECTS dd = DATE PANEL
    PROPERTIES vd = VALUE (dd)

    OBJECTS db = Debt
    PROPERTIES(db) numberContract, dateContract, nameLegalEntity, nameCustomer
    PROPERTIES(db) date, sum, numberAct, dateAct, nameAct
    PROPERTIES(db,dd) paidDop, balanceDop

    FILTERS NOT inactive(db),
            IF filterCustomerContractType() THEN type(contract(db)) == filterCustomerContractType() ELSE TRUE ,
            date(db) <= dd,
            (NOT balance(db) OR balance(db) = 0.00) AND balanceDop(db,dd) < 0.00
    ORDERS nameCustomer(db), nameLegalEntity(db), date(db)
;

reportNegativeDebts 'Скрытые переплаты' (DATE dd) {
    PRINT reportNegativeDebts OBJECTS dd = dd;
}

EXTEND FORM debtDashboard
    PROPERTIES reportNegativeDebts(dd)
;

DESIGN debtDashboard {
    BOX (dd) {
        MOVE PROPERTY (reportNegativeDebts(dd));
    }
}
